### ISSUE TITLE
v3.1.0 release overview

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#128]
[v3.1.0 Milestone](https://github.com/blockstack/blockstack.org/milestone/1)

### Highlights
- New blockstack brand design
- New communications on landing view

#### Tasks
- [x] https://github.com/blockstack/blockstack.org/issues/144: design header, update logo and rethink "code" dropdown
- [x] https://github.com/blockstack/blockstack.org/issues/149: design new subscribe to newsletter section
- [x] https://github.com/blockstack/blockstack.org/issues/110: design new hero section
- [x] https://github.com/blockstack/blockstack.org/issues/197: design new hero section (mobile)
- [x] https://github.com/blockstack/blockstack.org/issues/109: New hero illustration design
- [x] https://github.com/blockstack/blockstack.org/issues/191: design mobile navbar
- [x] https://github.com/blockstack/blockstack.org/issues/186: udpate blockstack architecture diagram on home view
- [x] https://github.com/blockstack/blockstack.org/issues/180: reposition banner image from blockstack.org blog posts
- [x] https://github.com/blockstack/blockstack.org/issues/175: Update the Blockstack favicon
- [x] https://github.com/blockstack/blockstack.org/issues/187: add new apple-touch-icons to metadata
- [x] https://github.com/blockstack/blockstack.org/pull/188: switched twitter card to large format
- [x] https://github.com/blockstack/blockstack.org/issues/176: Update the blockstack site snapshot for the metatags
- [x] https://github.com/blockstack/blockstack.org/issues/145: propose to change of "posts" wording in header
- [x] https://github.com/blockstack/blockstack.org/issues/199: build fixed scroll landing page with full screen height
- [x] https://github.com/blockstack/blockstack.org/issues/206: build new btn-secondary style with all states
- [x] https://github.com/blockstack/blockstack.org/issues/203: change landing view fonts to latest font set
- [x] https://github.com/blockstack/blockstack.org/issues/177: html/css build of header w/new logo on mobile
- [x] https://github.com/blockstack/blockstack.org/issues/210: build of new header w/logo on desktop
- [x] https://github.com/blockstack/blockstack.org/issues/212: build new btn-lg and primary btns
- [x] https://github.com/blockstack/blockstack.org/issues/213: build new dropdown button and menu
- [x] https://github.com/blockstack/blockstack.org/issues/215: add stats to landing view
- [x] https://github.com/blockstack/blockstack.org/issues/221: Maybe we should reduce links to the Github repos
- [x] https://github.com/blockstack/blockstack.org/issues/220: Slack link to archives from main page
- [x] https://github.com/blockstack/blockstack.org/issues/111: Unique URLs for documentation sections

#### Bugs
- [x] https://github.com/blockstack/blockstack.org/issues/190: bug: update twitter card for all pages
- [x] https://github.com/blockstack/blockstack.org/issues/198: bug: resolve data-reactroot div height issue
- [x] https://github.com/blockstack/blockstack.org/issues/200: bug: container overflow issue on mobile landing view
- [x] https://github.com/blockstack/blockstack.org/issues/202: bug: blog posts: insecure content
- [x] https://github.com/blockstack/blockstack.org/issues/207: bug: white space appears on landing view when scrolling
- [x] https://github.com/blockstack/blockstack.org/issues/205: bug: expand mobile landing view btn width beyond parent container
- [x] https://github.com/blockstack/blockstack.org/issues/214: bug: extra padding on some pages in navbar

#### Depricated
- [x] https://github.com/blockstack/blockstack.org/issues/113: design landing view (below the fold)

**Comment by guylepage3** [comment]
@shea256.
As per your recommendation, the **"join the community"** section has one goal, pushing the user to sign-up for the newsletter. User receives newsletter prompting them to join slack, reddit, meetup, medium and youtube.

**Comment by shea256** [comment]
Yeah here's the idea:

1. Have a large call to action which says "join the community" and then prompts the user for an email address.
2. The user immediately gets an email that says "welcome to the community" and shows a list of all the ways to get involved, including joining the slack, subscribing to the subreddit, joining a local meetup group, following the medium blog, and following the youtube channel.
3. The user is automatically signed up for the newsletter.
4. Optional: The user can automatically be sent a Slack invitation. The downside is the user will then receive two emails immediately upon signing up, but this could be worth it.

**Comment by shea256** [comment]
One more thing, once the user joins the community, the email they receive should primarily push the blockstack products. First, it should push the browser. Second, it should push the CLI.

For now, we can direct people to try the browser by joining the slack, but later we will be able to direct them to a download link.

Right now, we can direct people to the docs page to get started with the CLI.

**Comment by shea256** [comment]
Also, with this plan the sections would be laid out as follows:

- Hero
- News
- Blockstack Overview
- How Blockstack Works
- Building on Blockstack
- Blockstack Stats
- Who's on Blockstack
- Hello World Tutorial
- Join the Community
- Footer

**Comment by guylepage3** [comment]
>Also, with this plan the sections would be laid out as follows:
Yeah, I already have that list included in my list in the notes of this issue.

**Comment by shea256** [comment]
Yeah I saw but I modified it a bit.

**Comment by guylepage3** [comment]
@shea256 adding "subscribe" section to the list above

**Comment by guylepage3** [comment]
Based upon today's SCRUM meeting, I am deprecating `how blockstack works` from the landing view.

**Comment by guylepage3** [comment]
complete. https://github.com/blockstack/blockstack.org/issues/186: udpate blockstack architecture diagram on home view

**Comment by guylepage3** [comment]
complete. https://github.com/blockstack/blockstack.org/issues/175: Update the Blockstack favicon

**Comment by guylepage3** [comment]
complete. https://github.com/blockstack/blockstack.org/issues/187: add new apple-touch-icons to metadata

**Comment by guylepage3** [comment]
complete. https://github.com/blockstack/blockstack.org/pull/188: switched twitter card to large format

**Comment by guylepage3** [comment]
complete. #196: bug: resolve twitter summary card with large image sizing

**Comment by guylepage3** [comment]
complete. #198: resolve data-reactroot div height issue

**Comment by guylepage3** [comment]
complete. #199: build fixed scroll landing page with full screen height

**Comment by guylepage3** [comment]
reopened. #198: resolve data-reactroot div height issue

**Comment by guylepage3** [comment]
complete. #198: bug: resolve data-reactroot div height issue

**Comment by guylepage3** [comment]
complete. #197: design new hero section (mobile)

**Comment by guylepage3** [comment]
resolved. #200: bug: container overflow issue on mobile landing view

**Comment by guylepage3** [comment]
closing release
