### ISSUE TITLE
v3.2.0 release overview

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#129]
### Highlights
- Update to https://github.com/blockstack/blockstack-bootstrap
- Update documentation
- New full width navbar for all pages

#### Tasks
- [x] https://github.com/blockstack/blockstack.org/issues/235: Change "Install the Software" button copy to "Install Blockstack"
- [x] https://github.com/blockstack/blockstack.org/issues/236: Create page for installing packages from "Install Blockstack" button on home screen
- [x] https://github.com/blockstack/blockstack.org/issues/232: Add feed url to metadata
- [x] https://github.com/blockstack/blockstack.org/issues/229: add landing view background image for mobile, tablet & desktop
- [x] https://github.com/blockstack/blockstack.org/issues/219: design social proofs for landing view
- [x] https://github.com/blockstack/blockstack.org/issues/261: re-organize blockstack.org project structure
- [x] https://github.com/blockstack/blockstack.org/issues/244: Add a FAQs page
- [x] https://github.com/blockstack/blockstack.org/issues/270: merge all pr's into design branch

#### Bugs
- [x] https://github.com/blockstack/blockstack.org/issues/222: bug: navbar & contents shrink when nav-item docs is clicked on mobile
- [x] https://github.com/blockstack/blockstack.org/issues/196: bug: resolve twitter summary card with large image sizing
- [x] https://github.com/blockstack/blockstack.org/issues/201: bug: full screen on landing causes full screen on all views
- [x] https://github.com/blockstack/blockstack.org/issues/258: blog post image being cut on twitter desktop
- [x] https://github.com/blockstack/blockstack.org/issues/231: Resolve mobile view of blog post
- [x] https://github.com/blockstack/blockstack.org/issues/107: Cannot view docs

For reference: 
- https://api.blockstack.com/
- https://blockstack.org/docs

#### Pushed to [v4.0.0](https://github.com/blockstack/blockstack.org/projects/2)
- [ ] ~~https://github.com/blockstack/blockstack.org/issues/209: hamburger collapse menu dropdown~~
- [ ] ~~https://github.com/blockstack/blockstack.org/issues/239: redesign downloads view~~
- [ ] ~~https://github.com/blockstack/blockstack.org/issues/226: create new sign-up form page~~
- [ ] ~~https://github.com/blockstack/blockstack.org/issues/178: design new source code dropdown~~
- [ ] ~~https://github.com/blockstack/blockstack.org/issues/208: bug: lock all dragging movement on safari mobile~~
- [ ] ~~https://github.com/blockstack/blockstack.org/issues/211: build out mobile landscape viewport of landing view~~
- [ ] ~~https://github.com/blockstack/blockstack.org/issues/223: highlighting is broken~~
- [ ] ~~https://github.com/blockstack/blockstack.org/issues/227: Intro page link to Blockstack Core~~
- [ ] ~~https://github.com/blockstack/blockstack.org/issues/245: adjust size of landing view of the blockstack atlas grid illustration~~
- [ ] ~~https://github.com/blockstack/blockstack.org/issues/238: live design a support button for the landing view~~
- [ ] ~~https://github.com/blockstack/blockstack.org/issues/141: Unique URLs for documentation sections~~
- [ ] ~~https://github.com/blockstack/blockstack.org/issues/237: Transform "Docs" page to "Tutorials" page~~
- [ ] ~~https://github.com/blockstack/blockstack.org/issues/228: provide og meta data for block explorer post~~

#### Pushed to [v4.1.0](#)
- [ ] ~~https://github.com/blockstack/blockstack.org/issues/123: design a new full width navbar for all pages~~
- [ ] ~~https://github.com/blockstack/blockstack.org/issues/150: news~~
- [ ] ~~https://github.com/blockstack/blockstack.org/issues/179: html/css build of source code dropdown~~
- [ ] ~~https://github.com/blockstack/blockstack.org/issues/161: docs sidebar~~
- [ ] ~~https://github.com/blockstack/blockstack.org/issues/160: docs main content~~
- [ ] ~~https://github.com/blockstack/blockstack.org/issues/147: update html/scss in blockstack bootstrap~~
- [ ] ~~https://github.com/blockstack/blockstack.org/issues/184: design a launch screen image for ios mobile~~
- [ ] ~~https://github.com/blockstack/blockstack.org/issues/183: specify a launch screen image for ios mobile~~
- [ ] ~~https://github.com/blockstack/blockstack.org/issues/122: html/css build new full width navbar for all headers~~
- [ ] ~~https://github.com/blockstack/blockstack.org/issues/216: add social proofs to landing view~~
- [ ] ~~https://github.com/blockstack/blockstack.org/issues/181: update blog column to "width:700px;"~~
- [ ] ~~https://github.com/blockstack/blockstack.org/issues/182: update blog imagery~~
- [ ] ~~https://github.com/blockstack/blockstack.org/issues/185: add a launch icon title~~

**Comment by guylepage3** [comment]
Added new support and faq section to hightlights for this milestone

**Comment by guylepage3** [comment]
complete
