### ISSUE TITLE
v4.0.0 release overview

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#262]
### Highlights
- Redesign and new messaging to the blockstack.org landing page
- Design the join the community sign up page
- Redesign the download page

#### Tasks
- [x] https://github.com/blockstack/blockstack.org/issues/273: live design new landing view v1
- [x] https://github.com/blockstack/blockstack.org/issues/275: develop & live design new page template for hello blockstack tutorial
- [x] https://github.com/blockstack/blockstack.org/issues/209: hamburger collapse menu dropdown
- [x] https://github.com/blockstack/blockstack.org/issues/276: live design the landing view v2
- [x] https://github.com/blockstack/blockstack.org/issues/277: live design of the landing view v3
- [x] https://github.com/blockstack/blockstack.org/issues/278: live design of the landing view v4
- [x] https://github.com/blockstack/blockstack.org/issues/300: hero messaging creative brief
- [x] https://github.com/blockstack/blockstack.org/issues/292: design new landing view hero section and illustration
- [x] https://github.com/blockstack/blockstack.org/issues/302: home page content
- [x] https://github.com/blockstack/blockstack.org/issues/310: add background image to the hero section
- [x] https://github.com/blockstack/blockstack.org/issues/307: hero ui build 
- [x] https://github.com/blockstack/blockstack.org/issues/289: apply onename.com hamburger menu icon styles to site
- [x] https://github.com/blockstack/blockstack.org/issues/313: Add background color to extend hero image
- [x] https://github.com/blockstack/blockstack.org/issues/315: design new desktop header
- [x] https://github.com/blockstack/blockstack.org/issues/211: build out mobile landscape viewport of landing view
- [x] https://github.com/blockstack/blockstack.org/issues/316: ui build of new header for desktop view
- [x] https://github.com/blockstack/blockstack.org/issues/312: design & ui build of section 2 content landing view
- [x] https://github.com/blockstack/blockstack.org/issues/249: Blockstack.org landing view content
- [x] https://github.com/blockstack/blockstack.org/issues/332: design & ui build of section 3 content landing view
- [x] https://github.com/blockstack/blockstack.org/issues/333: design & ui build of section 4 content landing view
- [x] https://github.com/blockstack/blockstack.org/issues/336: design & UI build of section 5 content landing view
- [x] https://github.com/blockstack/blockstack.org/issues/338: update tutorials layout on landing view
- [x] https://github.com/blockstack/blockstack.org/issues/323: update hero design
- [x] https://github.com/blockstack/blockstack.org/issues/349: build v4.1 hero design ui
- [ ] https://github.com/blockstack/blockstack.org/issues/286: talk about blockchain agnostic (layer 2) on home page
- [ ] https://github.com/blockstack/blockstack.org/issues/303: Update newsletter onboarding content
- [ ] https://github.com/blockstack/blockstack.org/issues/339: update to tutorials code in svg's
- [ ] https://github.com/blockstack/blockstack.org/issues/334: add gradient background to section 3
- [ ] https://github.com/blockstack/blockstack.org/issues/239: redesign downloads view
- [ ] https://github.com/blockstack/blockstack.org/issues/226: create new sign-up form page
- [ ] https://github.com/blockstack/blockstack.org/issues/178: design new source code dropdown
- [ ] https://github.com/blockstack/blockstack.org/issues/256: Update link to join our community
- [ ] https://github.com/blockstack/blockstack.org/issues/238: live design a support button for the landing view
- [ ] https://github.com/blockstack/blockstack.org/issues/166: micro-interaction audit
- [ ] https://github.com/blockstack/blockstack.org/issues/141: Unique URLs for documentation sections
- [ ] https://github.com/blockstack/blockstack.org/issues/237: Transform "Docs" page to "Tutorials" page
- [ ] https://github.com/blockstack/blockstack.org/issues/228: provide og meta data for block explorer post
- [ ] https://github.com/blockstack/blockstack.org/issues/195: design block reveal effect to the blockstack sign-up form
- [ ] https://github.com/blockstack/blockstack.org/issues/194: proposal: add endless scroll of past blog posts to posts pages
- [ ] https://github.com/blockstack/blockstack.org/issues/193: revisit blog image design/placement
- [ ] https://github.com/blockstack/blockstack.org/issues/170: proposal: testimonials on blockstack.org
- [ ] https://github.com/blockstack/blockstack.org/issues/234: "Buzz" section on the top navbar
- [ ] https://github.com/blockstack/blockstack.org/issues/259: Blockstack.org landing page messaging
- [ ] https://github.com/blockstack/blockstack.org/issues/279: Request for Startups page content
- [ ] https://github.com/blockstack/blockstack.org/issues/322: create process for pull requests
- [ ] https://github.com/blockstack/blockstack.org/issues/321: Propose of new section: Partners / What's already on Blockstack
- [ ] https://github.com/blockstack/blockstack.org/issues/320: Brand color review

#### Bugs
- [x] https://github.com/blockstack/blockstack.org/issues/281: container width shrinking on landing view
- [x] https://github.com/blockstack/blockstack.org/issues/282: horizontal scroll issue on mobile view
- [x] https://github.com/blockstack/blockstack.org/issues/283: mobile navigation breakage
- [x] https://github.com/blockstack/blockstack.org/issues/284: animated gif being cutoff on landing mobile view
- [x] https://github.com/blockstack/blockstack.org/issues/314: Broken link on Blockstack Whitepaper: A New Decentralized Internet (Part I) blog page
- [x] https://github.com/blockstack/blockstack.org/issues/325: resolve issue with google font aliasing
- [x] https://github.com/blockstack/blockstack.org/issues/326: adjust type weight throughout site
- [x] https://github.com/blockstack/blockstack.org/issues/331: heading text center issue section 3
- [x] https://github.com/blockstack/blockstack.org/issues/165: mac instructions don't work on current macOS
- [x] https://github.com/blockstack/blockstack.org/issues/335: blockstack stack diagram svg image error
- [x] https://github.com/blockstack/blockstack.org/issues/337: add line breaks in landing view `<code>` tags
- [x] https://github.com/blockstack/blockstack.org/issues/309: adjust video div to be flush top, right and left to view port on tutorials item page
- [x] https://github.com/blockstack/blockstack.org/issues/366: fixed images on safari mobile not scaling
- [ ] https://github.com/blockstack/blockstack.org/issues/363: adjust width of all videos through out site on mobile
- [ ] https://github.com/blockstack/blockstack.org/issues/208: bug: lock all dragging movement on safari mobile
- [ ] https://github.com/blockstack/blockstack.org/issues/223: highlighting is broken
- [ ] https://github.com/blockstack/blockstack.org/issues/227: Intro page link to Blockstack Core
- [ ] https://github.com/blockstack/blockstack.org/issues/245: adjust size of landing view of the blockstack atlas grid illustration
- [ ] https://github.com/blockstack/blockstack.org/issues/116: Add “How to contribute?" to docs README.md
- [ ] https://github.com/blockstack/blockstack.org/issues/290: breakage of install page on mobile

#### Docs
- [ ] https://github.com/blockstack/blockstack.org/issues/108: 'Command Line - Basic Usage' doc doesn't mention that wallet needs to be created before running `blockstack price`

#### Deprecated
- [x] ~~https://github.com/blockstack/blockstack.org/issues/142: democracy earth logo update in landing site~~
- [x] ~~https://github.com/blockstack/blockstack.org/issues/143: add vchain logo and link to social proofs~~
