### ISSUE TITLE
v4.1.0 release overview

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#263]
### Highlights
- n/a

#### Tasks
- [ ] https://github.com/blockstack/blockstack.org/issues/238: live design a support button for the landing view
- [ ] https://github.com/blockstack/blockstack.org/issues/123: design a new full width navbar for all pages
- [ ] https://github.com/blockstack/blockstack.org/issues/150: news
- [ ] https://github.com/blockstack/blockstack.org/issues/179: html/css build of source code dropdown
- [ ] https://github.com/blockstack/blockstack.org/issues/161: docs sidebar
- [ ] https://github.com/blockstack/blockstack.org/issues/160: docs main content
- [ ] https://github.com/blockstack/blockstack.org/issues/147: update html/scss in blockstack bootstrap
- [ ] https://github.com/blockstack/blockstack.org/issues/184: design a launch screen image for ios mobile
- [ ] https://github.com/blockstack/blockstack.org/issues/183: specify a launch screen image for ios mobile
- [ ] https://github.com/blockstack/blockstack.org/issues/122: html/css build new full width navbar for all headers
- [ ] https://github.com/blockstack/blockstack.org/issues/216: add social proofs to landing view
- [ ] https://github.com/blockstack/blockstack.org/issues/181: update blog column to "width:700px;"
- [ ] https://github.com/blockstack/blockstack.org/issues/182: update blog imagery
- [ ] https://github.com/blockstack/blockstack.org/issues/185: add a launch icon title
- [ ] https://github.com/blockstack/blockstack.org/issues/189: resolve iphone app icon issue
- [ ] https://github.com/blockstack/blockstack.org/issues/193: revisit blog image design/placement
