### ISSUE TITLE
Request-For-Startup + Developer Release Roadmap page

### ISSUE THREAD

**Issue by pstan26** [blockstack/blockstack.org#293]
To support developers planning to build apps or contribute to the project we must make the vision for the future as clear as possible. The way I see it, and I think everyone would agree, a public plan with some dates is better than no plan listed at all. We can also use this roadmap as a TOC for tutorials.

Additionally, this Roadmap is a great place to have Requests-for-Startup where people can submit their pitches to Naval, Albert, and hopefully future angels.

I've transformed the App Possibilities doc created by @shea256 into the [draft for RFS +DRR page](https://paper.dropbox.com/doc/Requests-for-Startup-Dev-Release-Roadmap-7ZNgxAvkzqfNeWJHuhmmv). I think the sooner we get a page up like this the better -- this is an easy win.

Some action items:

@jcnelson :
- [ ] Create destination Repos for all tools (data storage, payment requests, data signing, etc) listed in the [draft for RFS +DRR page](https://paper.dropbox.com/doc/Requests-for-Startup-Dev-Release-Roadmap-7ZNgxAvkzqfNeWJHuhmmv).
- [ ] Add bold boiler plate message on how to contribute. It can be as simple as "contact me on slack"
- [ ] If the repo hasn’t been created, create one and just say coming soon, please star this — if there are any other things that can do to help push along the project, or resources they can use, add those. 
- [ ] Add Github URLs to Dropbox Paper draft Roadmap page

@shea256 : 
- [ ] read through [proposed RFS + DRR page](https://paper.dropbox.com/doc/Requests-for-Startup-Dev-Release-Roadmap-7ZNgxAvkzqfNeWJHuhmmv), add comments if necessary. @pstan26 will quickly copyedit.
- [ ] Create a “roadmap” repo on github.com/blockstack using newly supplied text (except for strikeout text) that mirrors to blockstack.org website, call it ‘blockstack.org/roadmap’
- [ ] Ask Albert and Naval if they are ok with the drafted RFS text at the top of the [doc](https://paper.dropbox.com/doc/Requests-for-Startup-Dev-Release-Roadmap-7ZNgxAvkzqfNeWJHuhmmv)
- [ ] Ask Naval to tell people to go to blockstack.org/roadmap during his techcrunch talk
- [ ] Create ‘funding@blockstack.org’  email group that goes to team@blockstack.com, route both funding+naval@blockstack.com  funding+albert@blockstack.com to go to both albert and naval emails. (we are using name in email this time for prestige and proof). 

(cc  @guylepage3 no action needed)
