### ISSUE TITLE
Upgrade to Bootstrap v4.0.0-beta

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#399]
Upgrade blockstack.org to Bootstrap v4.0.0-beta so that both the browser and website can share CSS and will be a consistent build environment. By upgrading we will also be moving in the right direction for deprecating Bootstrap altogether and moving over to our own design system.

**Reference:**
https://getbootstrap.com/

**Sections that need touching**
- [x] [#404: Remove all custom `@media` queries & rule sets](https://github.com/blockstack/blockstack.org/issues/404)
- [x] [#405: Update sticky social share to remove custom media query](https://github.com/blockstack/blockstack.org/issues/405)
- [x] [#406: Update to HTML5 doctype](https://github.com/blockstack/blockstack.org/issues/406)
- [x] [#407: Update to responsive meta-tags](https://github.com/blockstack/blockstack.org/issues/407)
- [x] [#411: Rebuild navbar to match new Bootstrap v4 navbar structure](https://github.com/blockstack/blockstack.org/issues/411)
- [x] [#398: Rebuild Token Banner to be an alert banner](https://github.com/blockstack/blockstack.org/issues/398)
- [x] [#403: Update all container, heading, centering & lead classes to work with Bootstrap v4](https://github.com/blockstack/blockstack.org/issues/403)

Components
- [x] Alert.js
- [x] Article.js
- [x] EmbedYouTube.js
- [x] Footer.js - [#415: Live design new footer](https://github.com/blockstack/blockstack.org/issues/415)
- [x] Header.js
- [x] PostPreview.js
- [x] PostShareWidget.js
- [x] Talk.js
- [x] TalkPreview.js
- [x] TeamMember.js
- [x] TeamMembers.js
- [x] TutorialPreview.js
- [x] VideoPresentation.js

Pages
- [x] ArticlePage.js
- [x] BlogPage.js
- [x] BlogPostPage.js
- [x] DocsPage.js
- [x] DownloadPage.js
- [x] FAQPage.js
- [x] HomePage.js
- [x] PapersPage.js
- [x] TalkPage.js
- [x] TalksPage.js
- [x] TokenSalePage.js
- [x] TutorialPage.js
- [x] TutorialsPage.js
- [x] FundingPage.js - [#424: Restructure funding page](https://github.com/blockstack/blockstack.org/issues/424)
- [ ] Summit2017Page.js
- [ ] CareersPage.js
- [ ] AboutPage.js
- [ ] SignUpPage.js
- [ ] IntroPage.js
- [ ] RoadmapPage.js
- [ ] NotFoundPage.js
- [ ] AuthPage.js
- [ ] BrowserPage.js
- [ ] DevSignUpPage.js
- [ ] SummitPage.js

**Comment by guylepage3** [comment]
Sections that need touching;
- [ ] Navbar
- [ ] Alert banner
- [ ] `containers
- [ ] Footer
- [ ] Centering of content
- [ ] Specialty `lead`'s

**Comment by guylepage3** [comment]
complete
