### ISSUE TITLE
Blockstack.org communications update

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#484]
Meeting w/ @shea256 @muneeb-ali @guylepage3

**Blockstack.org updates**
- [x] Home hero - Add Berlin banner https://github.com/blockstack/blockstack.org/issues/483
- [x] Home hero - Replace the main video with new video #491 
- [x] Home hero - Remove the stats section #492 
- [x] Home hero - Update hero graphic by adding new apps #493
- [x] Home featured apps - Update home page featured apps #495 
- [x] Home press section - Live design link or button to press page in press section on home page #496
- [x] Home press section - Home page replace WSJ article with VentureBeat token distribution article #497 
- [x] Videos - Update videos section #499
- [ ] About - Update [On HOLD - Waiting for feedback] see.. #500
- [x] Papers - Update papers page #501
- [x] Install - Update to the install page #502 
- [x] Install - Talk to @kantai about windows and linux about links on downloads. @kantai, can you address the above item? Complete. see https://github.com/blockstack/blockstack.org/issues/484#issuecomment-359919889
- [x] Tutorials - Have @jackzampolin go through the https://blockstack.org/tutorials again and document any changes & ask @pstan26 to see if a community member can go through these as well
- [x] Press - Update press page #503
- [x] Careers - Have @GinaAbrams update the markdown to add most important positions. Complete.
- [x] Careers - Move the careers link into the header. should be above the fold - pending review
- [x] Careers - Add Keyvalues link to Careers Page #505  - pending review
- [x] About - Add Chase to About Section #504 
- [ ] Newsletter archive - Blockstack newsletter archive page #508

**Blockstack.com updates**
- ~The "Read about the sale" link should link directly to the blog post~ - (I think we're going a different direction based on feedback from here https://github.com/blockstack/blockstack.org/issues/507)

**Other**
- FAQ - Have someone else update FAQ

**Comment by guylepage3** [comment]
- replace main video with new vid
- remove stats
- add berlin banner
- update hero graphic new apps
- update featured apps, coins, graphite, casa, afia, dotpodcast
- add link to press page in press section
- token sale to replace wsj article
- other teammate to update FAQ
- drop last 3 vids on .org and remove jeremy, albert, george
- update copy on about. remove the "in short". Mention 50M sale.
- papers just leave 2 papers.

.com
- articles link should go direct to post.

**Comment by guylepage3** [comment]
**Blockstack.org updates**
- [ ] Tutorials - Have @jackzampolin go through the tutorials again and document any changes & ask @pstan26 to see if a community member can go through these as well

**Comment by guylepage3** [comment]
- [ ] Install page - Talk to @kantai about windows and linux about links on downloads. 

@kantai, can you address the above item?

**Comment by guylepage3** [comment]
Aaron Blankstein [3:25 PM]
okay -- to me, the only change I would make is on the Linux (Advanced Install)
it should read somewhere  (Advanced, Docker installer, instructions here)
where _here_ links to
https://github.com/blockstack/packaging/tree/master/browser-core-docker#installing-blockstack-browser-and-api-with-docker

Guy Lepage [3:26 PM]
Are those builds working well?
Should we remove them until they are more stable?

Aaron Blankstein [3:27 PM]
yes they are working

Guy Lepage [3:27 PM]
ok cool. we’ll keep them in. thank you  sir.

**Comment by guylepage3** [comment]
Hey @jackzampolin have you had a chance to take a look at the above item.. https://github.com/blockstack/blockstack.org/issues/484#issuecomment-359888836

**Comment by jackzampolin** [comment]
I have! I've opened this PR to update the Todos tutorial: https://github.com/blockstack/blockstack/pull/409

**Comment by guylepage3** [comment]
perfecto. thank you sir. i just reviewed the PR. looks good.

**Comment by guylepage3** [comment]
@muneeb-ali @shea256 where would you like this newsletter archive to reside? https://us14.campaign-archive.com/home/?u=394a2b5cfee9c4b0f7525b009&id=0e5478ae86

**Comment by cwackerfuss** [comment]
Hey @guylepage3 and co -- the career-related tasks are now in a PR here!
https://github.com/blockstack/blockstack.org/pull/510

**Comment by guylepage3** [comment]
I just did a review @cwackerfuss. Looks great. I made one quick suggestion based upon the meeting @yknl, yourself and I had about organizing the CSS to get ready for an easier transition to SCSS or SASS.
